"""initial

Revision ID: 265765ad38f3
Revises: 
Create Date: 2025-10-26 22:47:00.597347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '265765ad38f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(btrim(name)) >= 1', name='ck_role_name_minlen'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    roles = [
        {'name': 'admin', 'description': 'Администратор платформы с полным доступом'},
        {'name': 'moderator', 'description': 'Модератор с лимитированным доступом, ограничивается администратором'},
        {'name': 'user', 'description': 'Обычный пользователь с базовым доступом'},
    ]
    conn = op.get_bind()
    conn.execute(
        sa.text("""
            INSERT INTO role_model (name, description)
            VALUES (:name, :description)
            ON CONFLICT (name) DO NOTHING
        """),
        roles
    )
    op.create_table('user_model',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('patronymic', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('first_name IS NULL OR char_length(btrim(first_name)) >= 1', name='ck_first_name_min_length'),
    sa.CheckConstraint('last_name IS NULL OR char_length(btrim(last_name)) >= 1', name='ck_last_name_min_length'),
    sa.CheckConstraint('patronymic IS NULL OR char_length(btrim(patronymic)) >= 1', name='ck_patronymic_min_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_model_email'), 'user_model', ['email'], unique=True)
    op.create_table('user_role_association',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role_model.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role_association')
    op.drop_index(op.f('ix_user_model_email'), table_name='user_model')
    op.drop_table('user_model')
    op.drop_table('role_model')
    # ### end Alembic commands ###
