"""initial

Revision ID: ca232f0bcf11
Revises: 
Create Date: 2025-11-04 18:04:49.643755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca232f0bcf11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_model',
    sa.Column('permission_level', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(btrim(name)) >= 1', name='ck_role_name_minlen'),
    sa.CheckConstraint('permission_level >= 0 AND permission_level <= 100', name='ck_role_permission_level_min_max'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    roles = [
        {'name': 'admin', 'description': 'Администратор платформы с полным доступом', 'permission_level': 100},
        {'name': 'lead_moderator', 'description': 'Старший модератор с расширенными правами', 'permission_level': 75},
        {'name': 'moderator', 'description': 'Средний модератор', 'permission_level': 50},
        {'name': 'junior_moderator', 'description': 'Младший модератор', 'permission_level': 30},
        {'name': 'user', 'description': 'Обычный пользователь с базовым доступом', 'permission_level': 10},
    ]
    conn = op.get_bind()
    conn.execute(
        sa.text("""
            INSERT INTO role_model (name, description, permission_level)
            VALUES (:name, :description, :permission_level)
            ON CONFLICT (name) DO UPDATE
            SET description = EXCLUDED.description,
                permission_level = EXCLUDED.permission_level
        """),
        roles
    )
    op.create_table('user_model',
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('patronymic', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('first_name IS NULL OR char_length(btrim(first_name)) >= 1', name='ck_first_name_min_length'),
    sa.CheckConstraint('last_name IS NULL OR char_length(btrim(last_name)) >= 1', name='ck_last_name_min_length'),
    sa.CheckConstraint('patronymic IS NULL OR char_length(btrim(patronymic)) >= 1', name='ck_patronymic_min_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_model_email'), 'user_model', ['email'], unique=True)
    op.create_table('user_role_association',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role_model.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role_association')
    op.drop_index(op.f('ix_user_model_email'), table_name='user_model')
    op.drop_table('user_model')
    op.drop_table('role_model')
    # ### end Alembic commands ###
